project 'YKRPC_POD_NAME_example.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YKRPC_POD_NAME_example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YKPRC_POD_NAMEExample
  pod 'YKRPC_POD_NAME', :path => '../'

end
