project 'YKRPC_POD_NAME_Example.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YKRPC_POD_NAME_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YKRPC_POD_NAME_Example
  pod 'YKRPC_POD_NAME', :path => '../'

end
