# read document if you don't understand something :)
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: YKRPC_POD_NAME_Example

options:
  minimumXcodeGenVersion: 2.10
  generateEmptyDirectories: true
  bundleIdPrefix: come.YKPRC_POD_Name.example
  developmentLanguage: en
#  postGenCommand: pod install

  deploymentTarget:
    iOS: "10.0"

fileGroups:
  - config/iOS

configs:
  Debug: DEBUG-NAME
  Release: RELEASE-NAME
  QDebug: QDEBUG-NAME
  QRelease: QRELEASE-NAME

configFiles:
  Debug: config/iOS/xcconfig/Project.debug.xcconfig
  Release: config/iOS/xcconfig/Project.release.xcconfig
  QDebug: config/iOS/xcconfig/Project.Qdebug.xcconfig
  QRelease: config/iOS/xcconfig/Project.Qrelease.xcconfig

include:
  - path: config/iOS.yml
    relativePaths: false
