# read document if you don't understand something :)
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: YKRPC_POD_NAME_Example
options:
  minimumXcodeGenVersion: 2.10
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  groupSortPosition: top
  groupOrdering:
    - order: [ config ]
    - pattern: YKRPC_POD_NAME_Example
      order: [ config ]    # - pattern: Component
      # order: [Demo, Base]
  generateEmptyDirectories: true
  bundleIdPrefix: come.YKPRC-POD-Name.example
  developmentLanguage: en
  # preGenCommand: |
  #   FILE=mazu/Resource/R.generated.swift
  #   if [ ! -f "$FILE" ]; then
  #     touch "$FILE"
  #     echo "Create R.swift because it not exist"
  #   fi
  postGenCommand: pod install

settings:

configs:
  Debug: DEBUG-NAME
  Release: RELEASE-NAME
configFiles:
  Debug: config/iOS/xcconfig/Project-Debug.xcconfig
  Release: config/iOS/xcconfig/Project-Release.xcconfig

### setting for each targets
# Targets
